### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Unoho** [udacity/MLND_CN_P1_Predicting_Housing_Price#1]
1.第一步 导入数据的最后一句话“提高房地产经纪的工作效率”
        建议改为“提高房地产经纪人的工作效率”
2.创造性：创造性主要是说两种情况，一种是对现有数据的处理，比如类别的One-hotEncoder独热编码或者LabelEncoder标签编码，数值的区间缩放，归一化标准化等等，另一种就是创造根据一些一个新的特征，例如某特征groupby后，或者某些特征组合后来创造新特征等等。
        建议改为“创造性：创造性主要是说两种情况，一种是对现有数据的处理，比如对类别的独热编码（One-hotEncoder）或者标签编码（LabelEncoder），数值的区间缩放，归一化，标准化等等，另一种就是根据某一个或多个特征创造一个新的特征，例如某特征groupby后，或者某些特征组合后来创造新特征等等。”
3.因为我们特别筛选出来的特征都为数值类型特征，所以我们只做标准化的操作：这个项目是一个回归的项目，而我们的回归算法对标准正太分步预测较为准确，从我们的目标数据可以看出数据是一个偏态分步，那么我们使用log将数据从偏态分步转换为标准正态分布，最后进行标准化。
         建议改为：因为我们筛选出来的特征都为数值类型特征，所以我们只做标准化的操作：这个项目是一个回归的项目，而我们的回归算法对标准正态分步预测较为准确，从我们的目标数据可以看出数据是一个偏态分步，那么我们使用log将数据从偏态分步转换为标准正态分布，最后进行标准化。
4.在项目的第四步，我们来看一下不同参数下，模型在训练集和验证集上的表现。这里，我们专注于一个特定的算法（带剪枝的决策树，但这并不是这个项目的重点），和这个算法的一个参数 'max_depth'。用全部训练集训练，选择不同'max_depth' 参数，观察这一参数的变化如何影响模型的表现。画出模型的表现来对于分析过程十分有益。
        建议：右括号后面的逗号应该可以删除
4.下方区域内的代码会输出四幅图像，它们是一个决策树模型在不同最大深度下的表现。每一条曲线都直观得显示了随着训练数据量的增加，模型学习曲线的在训练集评分和验证集评分的变化，评分使用决定系数  R2R2 。曲线的阴影区域代表的是该曲线的不确定性（用标准差衡量）。
        建议：‘’模型学习曲线”后面的“的”应该可以删除
5.复杂度曲线：运行下方区域中的代码，并利用输出的图形并回答下面的问题5与问题6。
       建议改为：运行下方区域中的代码，根据问题5与问题6对输出的图形进行分析并给出你思考的结果。

**Comment by DrTrippleJ** [comment]
谢谢你的反馈
