### ISSUE TITLE
语义不明确

### ISSUE THREAD

**Issue by juxingzhutou** [udacity/MLND_CN_P1_Predicting_Housing_Price#2]
![image](https://user-images.githubusercontent.com/7297350/51428786-d8aac400-1c42-11e9-9a13-d828ffbda95e.png)

红框中的Code和Markdown指的是notebook中的单元格，建议将红框中的文字修改为“代码和Markdown单元格”、“Markdown单元格”

**Comment by DrTrippleJ** [comment]
已修改，谢谢
